// Copyright 2026 The Sneakers-PAM Authors
// SPDX-License-Identifier: Apache-2.0

package shell

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/Sneakers-PAM/sneakers-appliance/internal/productinfo"
)

// The placeholders the reference shows for an installed product and a
// value it exposes.
var (
	refProduct = productinfo.Info{Name: "<product>", Title: "<Product>"}
	refValue   = Value{Name: "<value>", Label: "<Value label>"}
)

// Reference is docs/cli.md: every command of the closed shell, read from
// the command tree, with where it's offered, its usage, flags, keys and
// examples.
func Reference() string {
	ssh := Tree(OriginSSH, refProduct, refValue)
	console := Tree(OriginConsole, refProduct, refValue)
	hidden := map[string]bool{}
	walk(console, func(c *cobra.Command) { hidden[c.CommandPath()] = c.Hidden })

	var b strings.Builder
	b.WriteString("<!-- Generated by go run ./build/tools/clidoc from the closed shell's command tree; don't edit it by hand. -->\n\n")
	b.WriteString("# Closed-shell command reference\n\n")
	b.WriteString("Every command of the closed shell (`sneakers-shell`), the login shell of every admin over SSH and\n")
	b.WriteString("the menu on the console, as `help` shows it. How the shell splits a line, its errors and the\n")
	b.WriteString("root shell are in [ssh-and-elevation.md](ssh-and-elevation.md#the-closed-shell). `<product>`\n")
	b.WriteString("stands for the installed product's name (`sneakers`), and `<value>` for each value it exposes\n")
	b.WriteString("to the login's role.\n\n")
	fmt.Fprintf(&b, "%s\n\n", strings.TrimSpace(ssh.Long))
	b.WriteString("Every command takes `-o json` (`--output json`).\n")
	walk(ssh, func(c *cobra.Command) {
		if c == ssh {
			return
		}
		path := strings.TrimPrefix(c.CommandPath(), ssh.Name()+" ")
		var where []string
		if !c.Hidden {
			where = append(where, "SSH")
		}
		if !hidden[c.CommandPath()] {
			where = append(where, "console")
		}
		fmt.Fprintf(&b, "\n## `%s`\n\n%s.\n\n", path, strings.TrimSuffix(c.Short, "."))
		long, keys, _ := strings.Cut(c.Long, "\n\nKeys:\n")
		fmt.Fprintf(&b, "%s\n\n", strings.TrimSpace(long))
		if len(where) > 0 {
			fmt.Fprintf(&b, "Offered over: %s.\n\n", strings.Join(where, " and "))
		}
		use := strings.TrimPrefix(c.UseLine(), ssh.Name()+" ")
		if c.HasAvailableSubCommands() || c.HasSubCommands() {
			use = path + " <command>"
		}
		fmt.Fprintf(&b, "```text\n%s\n```\n", use)
		var flags []string
		c.LocalNonPersistentFlags().VisitAll(func(f *pflag.Flag) {
			if f.Name != "help" {
				flags = append(flags, fmt.Sprintf("| `--%s` | %s |", f.Name, f.Usage))
			}
		})
		if len(flags) > 0 {
			b.WriteString("\n| Flag | Meaning |\n|---|---|\n" + strings.Join(flags, "\n") + "\n")
		}
		if keys != "" {
			b.WriteString("\n| Key | Meaning | Example |\n|---|---|---|\n")
			for _, k := range keyRows(keys) {
				fmt.Fprintf(&b, "| `%s=` | %s | `%s` |\n", k[0], k[1], k[2])
			}
		}
		if c.HasSubCommands() {
			b.WriteString("\nIts commands:\n\n")
			for _, sub := range c.Commands() {
				fmt.Fprintf(&b, "- `%s`: %s\n", strings.TrimPrefix(sub.CommandPath(), ssh.Name()+" "), sub.Short)
			}
		}
		fmt.Fprintf(&b, "\nExample:\n\n```text\n%s\n```\n", c.Example)
	})
	return b.String()
}

func walk(c *cobra.Command, fn func(*cobra.Command)) {
	fn(c)
	for _, sub := range c.Commands() {
		walk(sub, fn)
	}
}

// keyRows reads keyList's lines back as name, help and example.
func keyRows(list string) [][3]string {
	var out [][3]string
	lines := strings.Split(strings.TrimRight(list, "\n"), "\n")
	for i := 0; i+1 < len(lines); i += 2 {
		name, help, _ := strings.Cut(strings.TrimSpace(lines[i]), "= ")
		ex := strings.TrimPrefix(strings.TrimSpace(lines[i+1]), "e.g. ")
		out = append(out, [3]string{name, strings.TrimSpace(help), ex})
	}
	return out
}
