name: Release Drafter
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update_release_draft:
    name: 📝 Update Release Draft
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Draft release notes
        uses: Bugs5382/release-drafter-action@9794698c9fc099feb314f49246ae0e82b1d1acb3  # v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          first-version: 0.1.0
